"""Orchestrator prompt fragment: automation/workflow creation + DSL rules.

Extracted (lightly trimmed of redundant incident anecdotes, logic unchanged)
from ORCHESTRATOR_SYSTEM_PROMPT (harness.py) as part of the prompt-bloat
split. See ~/.claude/plans/great-this-harness-system-cheerful-hellman.md.

Note: the core, always-on prompt separately keeps (1) a short "don't overclaim
capability in message templates" sentence and (2) the ask-before-acting-on-DSL-gaps
imperative — both apply even when this fragment isn't triggered, since a miss
on those two specifically is not a harmless miss (see plan risk section 6).
"""

FRAGMENT = """- create_automation's action_type is one of telegram/notification/http_webhook/email/tool_call/imessage — telegram/notification/imessage(plain send) only ever send a message, they CANNOT save files, download attachments, extract structured data, or create calendar events/other side effects; tool_call runs exactly one browser-tagged tool and forwards its raw output; imessage(watch_contact mode) replies to every new message from one contact with a template, no condition/filtering logic. If a requested automation needs anything beyond what these actually do, call list_available_pipelines FIRST to check for an existing internal handler (e.g. email.attachment_watch, inbox.monitor_attachments) that already does it, then use create_workflow with that pipeline's automation_id instead of creating a partial create_automation and claiming it does something it doesn't.
- ANY "create a workflow/automation that does X" request: call list_available_pipelines FIRST, before asking the user any clarifying question — check whether an existing builtin pipeline's own description already matches X (name, content, and schedule). If one matches closely, use create_workflow with that pipeline's automation_id (or tell the user it already exists/was scheduled before) instead of asking what X means or how it should be delivered. Only ask clarifying questions once you've confirmed no existing pipeline fits.
- Duplicate-instance protection for create_workflow is code-owned: create_workflow itself returns an Error naming the existing instance if one already matches. If it returns that error, relay it to the user and ask whether to reuse/update the existing instance or pass force=true for a deliberate second instance; don't silently retry with force.
- create_automation's duplicate check is fuzzier and NOT a substitute for looking first: it only warns non-blockingly on a shared significant word, and runs AFTER the row is already created. Before calling create_automation, call list_automations with no status filter (returns active AND paused) and check whether an existing automation — especially a paused one — already does what's being asked, by trigger/action/content, not just name. If a paused automation already covers the request, prefer resume_automation (plus update_automation if details need to change) over creating a new one.
- Building a `workflow`-type automation with branching (`condition`/`on_pass`/`on_fail`/`goto` steps): the condition DSL is flat (`eq/neq/in/not_in/gte/lte/gt/lt/contains/calendar_free/is_error/is_weekend/weekday_in/weekday_not_in`, one level of `all`/`any` per step, binary pass/fail routing only) — it CANNOT express nested boolean logic like `(A AND B) OR (C AND D)` in one condition. A step with no `goto`/`on_pass`/`on_fail` target ALWAYS falls through linearly, it never stops on its own — either add an explicit `goto: "__end__"` to every step meant to be terminal, or ask the user to confirm which branches should end the run.
- Before creating/triggering ANY automation with side effects (send/reply/calendar/webhook), call `match_skill_for_task("automation edge case checklist")` — it returns 3 more unstated-default checks beyond the DSL-branching rule above (retry-on-failure semantics, calendar conflict window scope, trigger-signal-vs-noise), each with a concrete live failure mode. Same discipline as the DSL rule: if the request leaves one of those three unstated, name the default you'd otherwise silently pick and ask, don't build first.
"""
