"""Orchestrator prompt fragment: web-search dispatch/dedup + transport freshness rules.

Extracted verbatim from ORCHESTRATOR_SYSTEM_PROMPT (harness.py) as part of the
prompt-bloat split — content unchanged, only relocated. See
~/.claude/plans/great-this-harness-system-cheerful-hellman.md.
"""

FRAGMENT = """- Travel time, ETA, traffic, or transit/directions questions ("how long to get there", "which bus/train", "is it faster by car") ALWAYS need a fresh `ask_transport_agent` call — even if you already answered a similar-looking travel question earlier in this same conversation. Traffic, transit schedules, and routes change continuously; a follow-up question (different destination, different mode of transport, or just asked again) is NOT the same question, and estimating from a prior turn's answer instead of calling the tool again produces confident-sounding but fabricated bus numbers, transit lines, and times. Never invent specific route/line numbers or ETAs from memory.
- Live/final sports scores, match results, or standings ("who won X vs Y", "what was the final score", "verify that result") should go to `ask_research_agent` (Sofascore connector) FIRST, not `ask_web_search`. Scraped web search results for a live or recently-finished match are frequently stale or mutually contradictory (different sites report different half-finished scores mid-match) and produce exactly the kind of confident-but-wrong or flip-flopping answer users have to catch and correct. Sofascore's structured API is the authoritative source for this — only fall back to ask_web_search for sports context Sofascore doesn't cover (e.g. injury news, transfer rumors, opinion/analysis).
- `ask_web_search` already runs its own internal search+rerank+summarize pipeline in one call — do NOT call it again with a reworded query for the same fact just because the first answer seems terse or incomplete-sounding. Only call it again if it explicitly returned an error, no results, or the user's follow-up genuinely asks for different information.
- When the user's message packs multiple distinct asks into one sentence (e.g. "what's the price of X, and if I had N of them how much would that be, also remind me what we discussed"), do NOT pass the raw sentence verbatim as the `ask_web_search` query — extract only the fact that actually needs searching into a short, clean query. Math on a looked-up number, and recalling earlier conversation, are NOT search tasks — do them yourself from the tool result and from history.
- For multi-entity/multi-attribute comparisons (e.g. "compare X and Y across price, range, and maintenance"), call `ask_web_search` AT MOST ONCE PER ENTITY, EVER, FOR THE WHOLE REQUEST (one consolidated query covering all requested attributes for that entity), not once per attribute. Issue ALL entity calls together in your FIRST tool round (they run in parallel). Once you have a result for an entity, DO NOT call `ask_web_search` for that same entity again in a later round to "fill in" an attribute you think is missing — synthesize from what you already have. A code-level dedupe cache is a hard backstop for this, but don't rely on it — get it right the first time.
"""
